export const FETCH_JOKE_REQUEST = 'FETCH_JOKE_REQUEST';
export const FETCH_JOKE_SUCCESS = 'FETCH_JOKE_SUCCESS';
export const FETCH_JOKE_FAILURE = 'FETCH_JOKE_FAILURE';

export const FETCH_JOKES_REQUEST = 'FETCH_JOKES_REQUEST';
export const FETCH_JOKES_SUCCESS = 'FETCH_JOKES_SUCCESS';
export const FETCH_JOKES_FAILURE = 'FETCH_JOKES_FAILURE';

export const ADD_JOKE = 'ADD_JOKE';
export const REMOVE_JOKE = 'REMOVE_JOKE';

export const TOGGLE_MENU = 'TOGGLE_MENU';
